version: '3'
services:
  web:
    build: /home/soosh/builds/django-meetups-rest/
    ports:
      - 62231:62231
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ENV_SECRET_KEY=${ENV_SECRET_KEY}
      #comma separated list but in settings.py need to split at comma for a list.
      - ALLOWED_HOSTS_ENV_STRING=${ALLOWED_HOSTS_ENV_STRING}
    volumes:
      - /home/soosh/builds/django-meetups-rest/:/code/
    #command: /bin/sh -c "./refresh.sh && gunicorn -b 0.0.0.0:62231 mysite.wsgi"
    command: /bin/sh -c "./refresh.sh && python3 manage.py runserver 0.0.0.0:62231"
    #command: sleep infinity
    depends_on:
      - db
    networks:
      - meetup_network
  db:
    #MYSQL
    image: mysql:8.0.26
    ports:
      - 3306:3306
    #hopefully this delays the loading of other containers that need 
    #this server to be using 'depends_on'
    healthcheck: 
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    #volumes: 
      #MYSQL
    #  - ./mysql:/var/lib/mysql 
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=t4nz4n14
    networks:
      - meetup_network

networks: 
  meetup_network:
