# Generated by Django 4.0 on 2022-01-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupgroup',
            name='description',
            field=models.CharField(default='default description', max_length=100),
        ),
    ]
