# Generated by Django 4.0 on 2022-01-03 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meetupgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupgroup',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='api.user'),
        ),
        migrations.AddField(
            model_name='meetupgroup',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
