# Generated by Django 4.0 on 2022-01-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_participants_alter_event_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='create_date',
            new_name='date_created',
        ),
    ]
