# Generated by Django 4.0 on 2022-01-07 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetupgroup',
            name='members',
            field=models.ManyToManyField(related_name='meetup_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetupgroup',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='create_date',
            field=models.DateField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meetup_groups',
            field=models.ManyToManyField(related_name='tags', to='api.MeetupGroup'),
        ),
    ]
