# Generated by Django 4.0.1 on 2022-02-08 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_participants_alter_meetupgroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetupgroup',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
